### ISSUE TITLE
replace GgrsConfig with Config

### ISSUE THREAD

**Issue by raphael384** [johanhelsing/johanhelsing.github.io#38]
Because we have implmented our own `Config`  we must replace `inputs: Res<PlayerInputs<GgrsConfig>>,` by ` inputs: Res<PlayerInputs<Config>>,` in the move_player function. (it's works for me)

**Comment by johanhelsing** [comment]
Thanks for the heads up. I found one occurence in part 1 and 3 in part 3. Let me know if you run into more problems!
